### ISSUE TITLE
how to modify the code to train a model without context conditioning?

### ISSUE THREAD

**Issue by irena123333** [fast-reflexes/MahlerNet#1]
Hi,

When I want to do the interpolation between 2 bars in a music peice, the given trained weights cannot work. Do you know how to train a model without context conditioning? Where should modify in the codes?

Thanks a lot!

**Comment by fast-reflexes** [comment]
Hi! 

Sorry for answering so late. This repo isn't really active in the way that development is still underway and that questions are addressed.

I don't 100% remember how it was but the docs on the main page says that interpolation is only supported for models trained WITHOUT context conditioning so I guess that's what you're after? The answer probably doesn't matter anymore but I think you're looking for the property `model.ctx` to be set to `False` to not model music with context in mind. :)
